### PR TITLE
ERD milestone 

### PR DESCRIPTION
**Pull request by rayking12**
Things to look out for:
- Entity relationship diagram in JPEG format

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @rayking12 and @Oxford-G  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, the ERD you implemented is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimum requirements of this project carefully, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The `Friendship` table is a bit tricky, think about it so carefully. Actually implementation of friendship feature involves the many-to-many relationship between table user and itself. Inorder to achieve that where comes the junction table `Friendship` => It should have one-to-many relationship on both sides. As a help: [read this article](https://support.airtable.com/hc/en-us/articles/218734758-Airtable-s-guide-to-many-to-many-relationships#manytomany) to learn more how to implement that junction table which make the many-to-many relationship possible. 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @Oxford-G & @rayking12, 👋🏽 
 **Thank you for the good job you got going on. The ERD is almost perfect.**

Just a few more changes to get it right.

## REQUIRED CHANGES

- [ ] Please fix the naming convention for your primary keys and foreign keys. For example, in the user table, the primary key for the user should be ID and not user_id. The latter is how you name a foreign key. Rectify this in all of your tables.
- [ ] Kindly review the usage of `one` and `one and only one` in your ERD.
- [ ] Will be better if you add the linter files for github checks.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @rayking12**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] you have to be consistent about what you write in the diagram tables. for example, you sometimes write the column name on the left and the column data_type on the right, but sometimes you do the opposite. the convention is that the column name goes to the left and the data_type goes to the right.  


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Gerald Enekwechi & King Ray** 
Good job with the improvements to your diagram :muscle:  :muscle: 
We still need to fix some details before you can go ahead:

- [ ] In your diagram, sometimes you have the name in the first column and sometimes you have it in the second column. It would be better to organized and define a specific purpose for each column. For example, the first column to indicate whether it is PK, FK or none, the second column for the name, and maybe a third column for the type. Check out this tutorial: https://www.youtube.com/watch?v=QpdhBUYk7Kk&ab_channel=Lucidchart
- [ ] In the User table, no need to indicate it has posts, comments and likes, you should only have there the values you will save each time you add a new user.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi @rayking12  & @Oxford-G**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
