### PR TITLE
Friendship model association created

### PR DESCRIPTION
**Pull request by rayking12**
Things to look at for:
- Friendship table created
- backend for users to send friendship invitation
- users can accept and deny a friendship invitation

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle: 

### Hi @rayking12 and @Oxford-G  !
 
#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.

**Recommended**
 
#### Behaviour

* [x] There is a button to invite a user to friendship on the users list page and on the single-user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- let's add these buttons to the mention views and make them work

* [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

* [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- You can do this by creating another view or have accept and decline buttons next to the name of the user who sent the friend request in the ALL USERS tab

* [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

- The timeline should only have the login user's post and his or her friend's post so let's create these validations for the views.

#### Test

- [x] I see you've added a test file, Please add unit test cases with Rspec and also create integration test cases with Rspec and Capybara at least for the Friendship features (Send, Accept, and Reject a Friend Request and see user and friends post in the Timeline).

### That's it, team! :raised_hands: 
 

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, great job on doing the required changes + the additional features you've added like deleting the sent friendship request and deleting a friend. Well done ✨🎉. However, there are still a few more changes to make in order to get this PR approved 😊🙏.

- [x] I guess you forgot to fix the requested issue from my teammate earlier about the timeline posts should only belong to the logged_in user and the users who are already friends with. Please add the proper logic to do that.
friends_timeline

- [x] There should be no logic in the views (currently your user views have logic inside them). Kindly move this logical code into the helpers, then call its methods back where you need inside the views.
- [x] Currently, there are empty and uncompleted test files. Please continue to add proper unit and integration tests for your app with covering both negative and positive scenarios
- [x] Please remove your credentials data from config/database.yml file (username and password shouldn't be located there)

<hr>

Kindly do the required changes and I believe you'll get this PR approved as soon as possible. 👍😊
Good luck and happy coding 👨‍💻💻

<hr>

You can always reach me out on Slack with the name "Mahmoud Bakr" if you have any question regarding anything 👌😊

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @Oxford-G & @rayking12, 👋🏽 
 **Thank you for the good job you got going on and making the requested changes**

## REQUIRED CHANGES

- [x] I'm not able to run all your tests successfully. Kindly ensure the correct usage of `require` and `require_relative` in the spec files.
- [ ] [OPTIONAL] Always ensure the correct application of git/github-flow. Use meaningful branch names instead of `milestone-five`. Also, the PR should be from your feature branch to develop branch 

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
Nice work. I was able to run all your tests successfully.
Merge and proceed to the next milestone.

### Martin Afani

**Pull request merged**
